spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Ffzu?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: "000000"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    localCacheScope: STATEMENT
    cache-enabled: false

